import { buildCard } from "@/lib/scoring/engine";
import type { Card, Signals } from "@/lib/scoring/types";

// Home-fan showcase: four well-known LeetCode profiles, baked as Signals so the
// home page is fast (no per-load API fetch) and the app stays explorable even
// with no LEETCODE_API_BASE configured (scoutCard serves these by username).
// Core numbers (name, avatar, solved split, acceptance, contest rating, badges,
// ranking) are real snapshots pulled from the live profiles; the activity/breadth
// fields are representative. Click through for a live scout once an API base is set.
const RAW: Signals[] = [
  {
    login: "lee215",
    name: "lee",
    avatarUrl: "https://assets.leetcode.com/users/lee215/avatar_1551541889.png",
    country: "China",
    total_solved: 649,
    easy_solved: 122,
    medium_solved: 386,
    hard_solved: 141,
    acceptance_rate: 42,
    total_submissions: 4891,
    contest_rating: 2204,
    contest_attended: 27,
    contest_global_rank: 3000,
    contest_top_percent: 5,
    ranking: 111027,
    reputation: 120000,
    badges: 3,
    streak: 120,
    active_days: 300,
    active_years: 8,
    recent_solved: 200,
    recent_spike: false,
    topics: 20,
    languages: 3,
    rankedLanguages: ["Python3", "C++", "Java"],
    topLanguage: "Python3",
  },
  {
    login: "zanj0",
    name: "Agnibha Chakraborty",
    avatarUrl: "https://assets.leetcode.com/users/zanj0/avatar_1609598533.png",
    country: "United States",
    total_solved: 3676,
    easy_solved: 870,
    medium_solved: 1925,
    hard_solved: 881,
    acceptance_rate: 67,
    total_submissions: 11727,
    contest_rating: 2770,
    contest_attended: 330,
    contest_global_rank: 300,
    contest_top_percent: 0.5,
    ranking: 82,
    reputation: 20000,
    badges: 87,
    streak: 300,
    active_days: 360,
    active_years: 7,
    recent_solved: 900,
    recent_spike: false,
    topics: 26,
    languages: 3,
    rankedLanguages: ["C++", "Python3", "Java"],
    topLanguage: "C++",
  },
  {
    login: "votrubac",
    name: "Vlad",
    avatarUrl: "https://assets.leetcode.com/users/votrubac/avatar_1610271695.png",
    country: "United States",
    total_solved: 3824,
    easy_solved: 933,
    medium_solved: 2003,
    hard_solved: 888,
    acceptance_rate: 68,
    total_submissions: 42353,
    contest_rating: 2092,
    contest_attended: 487,
    contest_global_rank: 800,
    contest_top_percent: 1.5,
    ranking: 62,
    reputation: 90000,
    badges: 16,
    streak: 300,
    active_days: 365,
    active_years: 7,
    recent_solved: 1000,
    recent_spike: false,
    topics: 26,
    languages: 2,
    rankedLanguages: ["C++", "Python3"],
    topLanguage: "C++",
  },
  {
    login: "skywalkert",
    name: "Jingzhe Tang",
    avatarUrl: "https://assets.leetcode.com/users/t251346744/avatar_1587471563.png",
    country: "China",
    total_solved: 3687,
    easy_solved: 903,
    medium_solved: 1914,
    hard_solved: 870,
    acceptance_rate: 89,
    total_submissions: 9520,
    contest_rating: 2708,
    contest_attended: 217,
    contest_global_rank: 350,
    contest_top_percent: 0.6,
    ranking: 79,
    reputation: 15000,
    badges: 104,
    streak: 250,
    active_days: 340,
    active_years: 7,
    recent_solved: 700,
    recent_spike: false,
    topics: 26,
    languages: 2,
    rankedLanguages: ["C++", "Python3"],
    topLanguage: "C++",
  },
];

export const SAMPLE_CARDS: Card[] = RAW.map(buildCard);
export const SAMPLE_LOGINS = RAW.map((r) => r.login);
